defaultAuthMethod:
  namespace: app
  enabled: true
  # Mount path for the Vault Auth Method.
  # @type: string
  mount: single-k8s-cluster-auth-mount
  method: kubernetes
  kubernetes:
    # Vault Auth Role to use
    # This is a required field and must be setup in Vault prior to deploying the helm chart
    # if `defaultAuthMethod.enabled=true`
    # @type: string
    role: "vso-auth-role"

    # Kubernetes ServiceAccount associated with the default Vault Auth Role
    # @type: string
    serviceAccount: default

    # Token Audience should match the audience of the vault kubernetes auth role.
    # @type: array<string>
    tokenAudiences: ["vault"]

defaultVaultConnection:
  enabled: true
  address: "http://vault.vault.svc.cluster.local:8200"
  skipTLSVerify: true
controller:
  replicas: 1