defaultVaultConnection:
  enabled: true
  address: "http://vault.vault.svc.cluster.local:8200"
  skipTLSVerify: false
controller:
  manager:
    clientCache:
      persistenceModel: direct-encrypted
      storageEncryption:
        enabled: true
        mount: single-k8s-cluster-auth-mount
        keyName: vso-client-cache
        transitMount: demo-transit
        kubernetes:
          role: vso-auth-role
          serviceAccount: demo-operator
