apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: app
spec:
  method: kubernetes
  mount: single-k8s-cluster-auth-mount
  kubernetes:
    role: vso-auth-role
    serviceAccount: default
    audiences:
      - vault