apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      test: app-demo
  template:
    metadata:
      labels:
        test: app-demo
    spec:
      volumes:
        - name: secrets
          secret:
            secretName: zone-v3-secret
      containers:
        - name: example
          image: nginx:latest
          envFrom:
            - secretRef:
                name: zone-v3-secret
          ### TRY IT ###
          # volumeMounts:
          #   - name: secrets
          #     mountPath: /etc/secrets
          #     readOnly: true
          resources:
            limits: 
              cpu: 50m
              memory: 50m
          livenessProbe:
            httpGet:
              path: /
              port: 80