apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: web-app-static-secret
  namespace: app
spec:
  type: kv-v2          # <-------- key-value version2
  mount: micro-service # <-------- vault mount path
  path: web-app        # <-------- 服務名稱

  # dest k8s secret
  destination:
    name: web-app-secret # <----- k8s secret name
    create: true

  refreshAfter: 30s
  vaultAuthRef: static-auth


